// Generated by LiveScript 1.2.0
var fetch;
fetch = function(query){
  query == null && (query = "字典");
  query = d3.select('#query').property('value');
  d3.select('#root').text("... 截取中 ...");
  return d3.html("https://moedict.tw/" + query, function(d){
    var str;
    str = "";
    d3.select(d).selectAll(".fw_def").each(function(){
      return str += d3.select(this).text() + "\n";
    });
    if (!str) {
      str = "找不到這個詞 :(";
    } else {
      str = query + " 的外語寫法如下: \n" + str;
    }
    return d3.select('#root').text(str);
  });
};
fetch();